calc elevation min & max on study area
UrbanSystemsLab/climateiq-cnn pull request #28
Opened 2024-04-19 20:53 UTC by waltaskew

2024-04-22 20:08 UTC, rsutormin requested changes

2024-04-22 20:34 UTC, waltaskew commented on usl_pipeline/cloud_functions/main.py
> +        rasterio.io.MemoryFile(fd.read())
These are the chunks, so we should be fine.

2024-04-22 20:35 UTC, waltaskew commented on usl_pipeline/cloud_functions/main.py
> +    metadata = {
Can you make a more concrete suggestion for improvement?

2024-04-22 21:30 UTC, rsutormin commented on usl_pipeline/cloud_functions/main.py
> +    metadata = {
Yeah, I mean some structure with typed fields with verifiable field names. For now you can make a typo in a field key string (or if you expect to see something other than float as a value) and nothing would warn you except if you make some integration tests.

2024-04-23 00:02 UTC, waltaskew commented on usl_pipeline/cloud_functions/main.py
> +    metadata = {
I agree, this is better as a struct. Done.

2024-04-23 16:11 UTC, rsutormin approved these changes

2024-04-23 16:22 UTC, merged